version: '3.6'
services:
  api: &api
    image: quickpickup:api
    build:
      context: ./api
      target: ${DOCKER_BUILD_API_TARGET:-final}
    command: flask run --host 0.0.0.0 --port 8080
    environment:
      FLASK_APP: quickpickup.api
    links:
      - mongo
      - chatbot
    ports:  # Public ports for direct debugging
      - 8080:8080

  nginx:
    image: quickpickup:nginx
    build:
      context: ./ui
    links:
      - api
    ports:
      - 80:80
    command: [nginx-debug, '-g', 'daemon off;']

  mongo:
    image: mongo
    ports:  # Public ports for direct debugging
      - 27017:27017
    logging:
      driver: none

  chatbot:
    image: quickpickup:chatbot
    build:
      context: ./chat
    environment:
      ROOM_NAME: ${ROOM_NAME:-test}
      WEBEX_BOT_USERNAME: ${WEBEX_BOT_USERNAME:-test}
      WEBEX_TEAMS_ACCESS_TOKEN: ${WEBEX_TEAMS_ACCESS_TOKEN:-test}
    ports:
      - 5030:5030

  mvsensor:
    image: quickpickup:mvsensor
    build:
      context: ./mvsensor
    environment:
      MVSENSOR_API_KEY: ${MVSENSOR_API_KEY:-test}
      MVSENSOR_SERIAL: ${MVSENSOR_SERIAL:-test}
      MVSENSOR_WEBHOOK_URL: ${MVSENSOR_WEBHOOK_URL:-http://chatbot:5030}
      MVSENSOR_DBAPI_URL: ${MVSENSOR_DBAPI_URL:-http://api:8080}
    links:
      - chatbot

  api-test:
    <<: *api
    image: quickpickup:test
    build:
      context: ./api
      target: test
    ports: []
    command: pytest -vv --color=yes ./test
