version: '3.3'
services:
  api:
    image: quickpickup:api
    build:
      context: .
    links:
      - mongo
      - chatbot

  nginx:
    image: quickpickup:nginx
    build:
      context: ./ui
    links:
      - api
    ports:
      - 80:80

  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db

  chatbot:
    image: quickpickup:chatbot
    build:
      context: ./chat
    environment:
      ROOM_NAME: ${ROOM_NAME}
      WEBEX_BOT_USERNAME: ${WEBEX_BOT_USERNAME}
      WEBEX_TEAMS_ACCESS_TOKEN: ${WEBEX_TEAMS_ACCESS_TOKEN}

  mvsensor:
    image: quickpickup:mvsensor
    build:
      context: ./mvsensor
    environment:
      MVSENSOR_API_KEY: ${MVSENSOR_API_KEY}
      MVSENSOR_SERIAL: ${MVSENSOR_SERIAL}
      MVSENSOR_WEBHOOK_URL: ${MVSENSOR_WEBHOOK_URL}
    links:
      - chatbot

volumes:
  mongodata:
