version: '3.3'
services:
  api:
    image: quickpickup
    build:
      context: .
    environment:
      MONGO_URI: 'mongodb://mongo:27017'
    links:
      - mongo
    ports:  # Public ports for direct debugging
      # TODO: Remove this when we have an nginx proxy
      - 8080:8080

  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db

  chatbot:
    image: webex_teams_chatbot
    build:
      context: .
      dockerfile: Dockerfile.chat
    env_file: chat.env

volumes:
  mongodata:

