version: '3.6'
services:
  api: &api
    image: quickpickup
    build:
      context: .
      target: ${DOCKER_BUILD_API_TARGET:-final}
    # TODO: Refactor to split development mode from production
    command: flask run --host 0.0.0.0 --port 8080
    environment:
      FLASK_APP: quickpickup.api
      MONGO_URI: 'mongodb://mongo:27017'
    links:
      - mongo
    ports:  # Public ports for direct debugging
      - 8080:8080
  mongo:
    image: mongo
    ports:  # Public ports for direct debugging
      - 27017:27017
    # TODO: Volume mounts for "production" data so we don't lose anything on
    # restarts
  chatbot:
    image: webex_teams_chatbot
    build:
      context: .
      dockerfile: Dockerfile-chat
    env_file: chat.env
    networks:
      - "backend_network"
    ports:
      - 5030:5030
  test:
    <<: *api
    image: quickpickup:test
    build:
      context: .
      target: test
    environment:
      MONGO_URI: 'mongodb://mongo:27017'
      INTEGRATION_TEST: 'True'
    ports: []
    command: pytest -v --color=yes ./test
networks:
  backend_network:
    driver: "bridge"
  frontend_network:
    driver: "bridge"
